"""Sample catalog data for AutoHub — cars and parts.

Images use Unsplash URLs so the demo renders without local assets.
Swap these for your own product photos when you go live.
"""

CARS = [
    {
        "id": "toyota-camry-2024",
        "name": "Toyota Camry SE",
        "brand": "Toyota",
        "year": 2024,
        "category": "sedan",
        "condition": "New",
        "price": 28500000,
        "mileage_km": 0,
        "transmission": "Automatic",
        "fuel": "Petrol",
        "color": "Pearl White",
        "featured": True,
        "image": "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
        "description": "The 2024 Camry SE blends comfort and efficiency with a refined 2.5L engine, sport-tuned suspension, and a full suite of Toyota Safety Sense features.",
        "specs": {"Engine": "2.5L 4-Cylinder", "Power": "203 hp", "Drivetrain": "FWD", "Seats": "5"},
    },
    {
        "id": "honda-crv-2023",
        "name": "Honda CR-V EX",
        "brand": "Honda",
        "year": 2023,
        "category": "suv",
        "condition": "Foreign Used",
        "price": 32000000,
        "mileage_km": 18500,
        "transmission": "Automatic",
        "fuel": "Petrol",
        "color": "Sonic Grey",
        "featured": True,
        "image": "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&q=80",
        "description": "Spacious, reliable, and fuel-efficient. This CR-V EX comes with AWD, a panoramic roof, and Honda Sensing driver assistance.",
        "specs": {"Engine": "1.5L Turbo", "Power": "190 hp", "Drivetrain": "AWD", "Seats": "5"},
    },
    {
        "id": "mercedes-c300-2022",
        "name": "Mercedes-Benz C300",
        "brand": "Mercedes-Benz",
        "year": 2022,
        "category": "sedan",
        "condition": "Foreign Used",
        "price": 45000000,
        "mileage_km": 27400,
        "transmission": "Automatic",
        "fuel": "Petrol",
        "color": "Obsidian Black",
        "featured": True,
        "image": "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
        "description": "Luxury redefined. The C300 offers a turbocharged engine, MBUX infotainment, and a hand-stitched leather interior.",
        "specs": {"Engine": "2.0L Turbo", "Power": "255 hp", "Drivetrain": "RWD", "Seats": "5"},
    },
    {
        "id": "lexus-rx350-2021",
        "name": "Lexus RX 350",
        "brand": "Lexus",
        "year": 2021,
        "category": "suv",
        "condition": "Foreign Used",
        "price": 52000000,
        "mileage_km": 41200,
        "transmission": "Automatic",
        "fuel": "Petrol",
        "color": "Nebula Grey",
        "featured": True,
        "image": "https://images.unsplash.com/photo-1606016159991-8b5d5f9f5a0f?w=800&q=80",
        "description": "Premium comfort SUV with a smooth V6, whisper-quiet cabin, and Lexus legendary reliability.",
        "specs": {"Engine": "3.5L V6", "Power": "295 hp", "Drivetrain": "AWD", "Seats": "5"},
    },
    {
        "id": "ford-mustang-2023",
        "name": "Ford Mustang GT",
        "brand": "Ford",
        "year": 2023,
        "category": "sports",
        "condition": "New",
        "price": 68000000,
        "mileage_km": 0,
        "transmission": "Manual",
        "fuel": "Petrol",
        "color": "Race Red",
        "featured": True,
        "image": "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=800&q=80",
        "description": "American muscle at its finest. A 5.0L V8, aggressive styling, and a soundtrack that turns heads.",
        "specs": {"Engine": "5.0L V8", "Power": "480 hp", "Drivetrain": "RWD", "Seats": "4"},
    },
    {
        "id": "tesla-model3-2024",
        "name": "Tesla Model 3",
        "brand": "Tesla",
        "year": 2024,
        "category": "electric",
        "condition": "New",
        "price": 41000000,
        "mileage_km": 0,
        "transmission": "Automatic",
        "fuel": "Electric",
        "color": "Deep Blue",
        "featured": True,
        "image": "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80",
        "description": "All-electric performance with 500km range, autopilot, and over-the-air updates. The future of driving.",
        "specs": {"Range": "513 km", "Power": "283 hp", "Drivetrain": "RWD", "Seats": "5"},
    },
    {
        "id": "toyota-hilux-2022",
        "name": "Toyota Hilux Double Cab",
        "brand": "Toyota",
        "year": 2022,
        "category": "truck",
        "condition": "Foreign Used",
        "price": 38500000,
        "mileage_km": 33000,
        "transmission": "Manual",
        "fuel": "Diesel",
        "color": "Silver",
        "featured": False,
        "image": "https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&q=80",
        "description": "The unbreakable workhorse. 4WD, diesel torque, and a payload built for any terrain.",
        "specs": {"Engine": "2.8L Diesel", "Power": "204 hp", "Drivetrain": "4WD", "Seats": "5"},
    },
    {
        "id": "bmw-x5-2021",
        "name": "BMW X5 xDrive40i",
        "brand": "BMW",
        "year": 2021,
        "category": "suv",
        "condition": "Foreign Used",
        "price": 58000000,
        "mileage_km": 46800,
        "transmission": "Automatic",
        "fuel": "Petrol",
        "color": "Alpine White",
        "featured": False,
        "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        "description": "Sporty luxury SUV with a silky inline-6, adaptive suspension, and cutting-edge iDrive tech.",
        "specs": {"Engine": "3.0L Turbo I6", "Power": "335 hp", "Drivetrain": "AWD", "Seats": "5"},
    },
]

PARTS = [
    {
        "id": "brake-pads-ceramic",
        "name": "Ceramic Brake Pads (Front Set)",
        "brand": "Bosch",
        "category": "brakes",
        "condition": "New",
        "price": 45000,
        "featured": True,
        "image": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&q=80",
        "description": "Low-dust, long-life ceramic brake pads for quiet, reliable stopping power. Fits most sedans and SUVs.",
        "fits": "Toyota, Honda, Lexus",
    },
    {
        "id": "oil-filter-premium",
        "name": "Premium Oil Filter",
        "brand": "Mann-Filter",
        "category": "engine",
        "condition": "New",
        "price": 8500,
        "featured": True,
        "image": "https://images.unsplash.com/photo-1635784063388-1ff609e4a1b6?w=800&q=80",
        "description": "High-flow oil filter with premium filtration media for cleaner oil and longer engine life.",
        "fits": "Universal (check size)",
    },
    {
        "id": "alloy-wheels-18",
        "name": "18-inch Alloy Wheels (Set of 4)",
        "brand": "Enkei",
        "category": "wheels",
        "condition": "New",
        "price": 420000,
        "featured": True,
        "image": "https://images.unsplash.com/photo-1626668893632-6f3a4466d22f?w=800&q=80",
        "description": "Lightweight forged alloy wheels for improved handling and a sharp, modern look. 5x114.3 bolt pattern.",
        "fits": "Most 5-lug vehicles",
    },
    {
        "id": "led-headlight-kit",
        "name": "LED Headlight Conversion Kit",
        "brand": "Philips",
        "category": "electrical",
        "condition": "New",
        "price": 32000,
        "featured": True,
        "image": "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80",
        "description": "6000K ultra-bright LED bulbs with plug-and-play install. 3x brighter than halogen, 30,000-hour lifespan.",
        "fits": "H4 / H7 / H11 fitments",
    },
    {
        "id": "car-battery-70ah",
        "name": "Maintenance-Free Battery 70Ah",
        "brand": "Exide",
        "category": "electrical",
        "condition": "New",
        "price": 68000,
        "featured": False,
        "image": "https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=800&q=80",
        "description": "Sealed maintenance-free battery with high cold-crank amps and an 18-month warranty.",
        "fits": "Most sedans & SUVs",
    },
    {
        "id": "air-filter-performance",
        "name": "Performance Air Filter",
        "brand": "K&N",
        "category": "engine",
        "condition": "New",
        "price": 22000,
        "featured": False,
        "image": "https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=800&q=80",
        "description": "Washable, reusable high-flow air filter for improved airflow and throttle response. Lasts up to 80,000 km.",
        "fits": "Vehicle-specific (confirm model)",
    },
    {
        "id": "wiper-blades-set",
        "name": "All-Season Wiper Blades (Pair)",
        "brand": "Bosch",
        "category": "accessories",
        "condition": "New",
        "price": 12000,
        "featured": False,
        "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
        "description": "Aerodynamic beam blades for streak-free wiping in rain and dust. Easy clip-on install.",
        "fits": "Universal sizes 16-26 inch",
    },
    {
        "id": "floor-mats-rubber",
        "name": "All-Weather Rubber Floor Mats",
        "brand": "WeatherTech",
        "category": "accessories",
        "condition": "New",
        "price": 35000,
        "featured": False,
        "image": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
        "description": "Custom-fit rubber mats that trap dirt, mud, and water. Deep channels keep your interior spotless.",
        "fits": "Model-specific fitment",
    },
]

CAR_CATEGORIES = [
    {"slug": "sedan", "name": "Sedans", "image": "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=600&q=80"},
    {"slug": "suv", "name": "SUVs", "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&q=80"},
    {"slug": "truck", "name": "Trucks & Pickups", "image": "https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=600&q=80"},
    {"slug": "sports", "name": "Sports Cars", "image": "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&q=80"},
    {"slug": "electric", "name": "Electric", "image": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80"},
]

PART_CATEGORIES = [
    {"slug": "brakes", "name": "Brakes"},
    {"slug": "engine", "name": "Engine"},
    {"slug": "wheels", "name": "Wheels & Tyres"},
    {"slug": "electrical", "name": "Electrical"},
    {"slug": "accessories", "name": "Accessories"},
]

BRANDS = sorted({c["brand"] for c in CARS})
